# Generated by Django 4.0 on 2022-06-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('supervisor', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='type_of_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofLeave', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.DateField()),
                ('tdate', models.DateField()),
                ('type_of_leave', models.CharField(default='', max_length=20)),
                ('reason', models.CharField(default='', max_length=500)),
                ('authuser', models.ForeignKey(db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('status', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='lleave.progressbar')),
            ],
        ),
    ]
