# Generated by Django 4.0 on 2022-06-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lleave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.ForeignKey(db_constraint=False, default=True, on_delete=django.db.models.deletion.CASCADE, to='lleave.progressbar'),
        ),
    ]
