# Generated by Django 4.0 on 2022-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lleave', '0002_alter_leaveapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuss', models.CharField(max_length=50)),
            ],
        ),
    ]
