# Generated by Django 4.0 on 2022-06-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lleave', '0003_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
