# Generated by Django 4.0 on 2022-06-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lleave', '0006_alter_leaveapplication_status_delete_progressbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='Reject'),
        ),
    ]
