# Generated by Django 4.0 on 2022-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lleave', '0007_leaveapplication_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='pending',
            field=models.BooleanField(default=True, verbose_name='Pending'),
        ),
    ]
